let role='teacher';
let students=JSON.parse(localStorage.getItem('students')||'["Нұрлан Әли — 8А","Айша Ермек — 9Б"]');
let achievements=JSON.parse(localStorage.getItem('achievements')||'[{"person":"Нұрлан Әли","type":"Диплом","competition":"Математика олимпиадасы","level":"Облыстық","place":"II орын","year":"2026"},{"person":"Айша Ермек","type":"Грамота","competition":"Ғылыми жоба","level":"Республикалық","place":"I орын","year":"2026"}]');
function login(){let u=email.value,p=password.value;if((u==='teacher'&&p==='1234')||(u==='admin'&&p==='admin')){role=u==='admin'?'admin':'teacher';loginEl=document.getElementById('login');loginEl.classList.add('hidden');app.classList.remove('hidden');who.innerHTML=role==='admin'?'👑 Әкімші':'👩‍🏫 Мұғалім';adminBtn.style.display=role==='admin'?'block':'none';show('dashboard');render()}else alert('Логин немесе құпиясөз қате')}
function logout(){app.classList.add('hidden');document.getElementById('login').classList.remove('hidden')}
function show(id){document.querySelectorAll('main section').forEach(x=>x.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');render()}
function render(){total.textContent=achievements.length;studentCount.textContent=students.length;repCount.textContent=achievements.filter(x=>x.level==='Республикалық').length;aStudents.textContent=students.length;aAchievements.textContent=achievements.length;recent.innerHTML=achievements.slice(-4).reverse().map(card).join('')||'<p>Әзірге жетістік жоқ.</p>';studentList.innerHTML=students.map(x=>`<div class="student"><b>👨‍🎓 ${x}</b><p>${achievements.filter(a=>x.includes(a.person)).length} жетістік</p></div>`).join('');renderAchievements()}
function card(a){return `<div class="item"><div><b>${a.person}</b><div>${a.competition} · ${a.place||'Нәтиже көрсетілмеген'} · ${a.year}</div></div><span class="badge">${a.level}</span></div>`}
function renderAchievements(){if(!document.getElementById('achievementList'))return;let q=(search.value||'').toLowerCase();achievementList.innerHTML=achievements.filter(a=>JSON.stringify(a).toLowerCase().includes(q)).map(card).join('')||'<p>Нәтиже табылмады.</p>'}
function addStudent(){let n=prompt('Оқушының аты-жөні және сыныбы (мысалы: Аружан Серік — 7А)');if(n){students.push(n);localStorage.setItem('students',JSON.stringify(students));render()}}
function saveAchievement(e){e.preventDefault();let f=document.getElementById('file').files[0];achievements.push({person:person.value,type:type.value,competition:competition.value,level:level.value,place:place.value,year:year.value,file:f?f.name:''});localStorage.setItem('achievements',JSON.stringify(achievements));e.target.reset();year.value=2026;alert('Жетістік сақталды!');show('achievements')}
render();
